dist: bionic
sudo: false
language: cpp
branches:
  only:
    - master
git:
  depth: 1

jobs:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
        - CXX_COMPILER="-DCMAKE_CXX_COMPILER=g++-9"
        - BUILD_CONFIG=

    - os: linux
      arch: arm64
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
        - CXX_COMPILER="-DCMAKE_CXX_COMPILER=g++-9"
        - BUILD_CONFIG=

    - os: linux
      arch: amd64
      compiler: clang
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
      env:
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
        - CXX_COMPILER="-DCMAKE_CXX_COMPILER=clang-9"
        - BUILD_CONFIG=

    - os: linux
      arch: arm64
      compiler: clang
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
      env:
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
        - CXX_COMPILER="-DCMAKE_CXX_COMPILER=clang-9"
        - BUILD_CONFIG=

    - os: windows
      arch: amd64
      env:
        - BUILD_TYPE=
        - CXX_COMPILER=
        - BUILD_CONFIG="--config Release"

script:
  - mkdir build
  - cd build
  - cmake $BUILD_TYPE $CXX_COMPILER ..
  - cmake --build . $BUILD_CONFIG