dist: bionic
language: cpp
branches:
  only:
    - master
git:
  depth: 1

cmake_build_script: &cmake_build_script
  - |-
    if [ ! -f $CMAKE ]; then
      cd $HOME
      wget https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2.tar.gz
      tar -xf cmake-3.16.2.tar.gz
      mkdir cmake
      cmake-3.16.2/bootstrap --prefix=$HOME/cmake --parallel=$(nproc)
      make
      make install
      rm -rf cmake-3.16.2.tar.gz cmake-3.16.2/
      cd -
    fi

jobs:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
        - CXX_COMPILER="-DCMAKE_CXX_COMPILER=g++-9"
        - BUILD_CONFIG=
        - CMAKE=$HOME/cmake/bin/cmake
      before_script:
        *cmake_build_script
      cache:
        directories:
          - $HOME/cmake

    - os: linux
      arch: arm64
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
        - CXX_COMPILER="-DCMAKE_CXX_COMPILER=g++-9"
        - BUILD_CONFIG=

    - os: linux
      arch: amd64
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
      env:
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
        - CXX_COMPILER="-DCMAKE_CXX_COMPILER=clang++-9"
        - BUILD_CONFIG=

    - os: windows
      arch: amd64
      env:
        - BUILD_TYPE=
        - CXX_COMPILER=
        - BUILD_CONFIG="--config Release"

script:
  - mkdir build
  - cd build
  - $CMAKE $BUILD_TYPE $CXX_COMPILER -DCMAKE_UNITY_BUILD=ON ..
  - $CMAKE --build . $BUILD_CONFIG
