dist: bionic
language: cpp
branches:
  only:
    - master
git:
  depth: 1

_cmake_env: &_cmake_env
  - MY_CMAKE_DIR=$HOME/cmake
  - MY_CMAKE=$MY_CMAKE_DIR/bin/cmake
_cmake_build_script: &_cmake_build_script
  - |-
    if [ ! -f $MY_CMAKE ]; then
      rm -rf MY_CMAKE_DIR
      wget -P $HOME https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2.tar.gz
      mkdir $MY_CMAKE_DIR
      mkdir $MY_CMAKE_DIR/src
      tar -C $MY_CMAKE_DIR/src -xf $HOME/cmake-3.16.2.tar.gz
      cmake -S $MY_CMAKE_DIR/src/cmake-3.16.2 -B $MY_CMAKE_DIR/src/cmake-3.16.2/build
      cmake --build $MY_CMAKE_DIR/src/cmake-3.16.2/build -j $(nproc)
      cmake --install $MY_CMAKE_DIR/src/cmake-3.16.2/build --prefix $MY_CMAKE_DIR
      rm -rf $HOME/cmake-3.16.2.tar.gz $MY_CMAKE_DIR/src/
    fi
_cmake_cache_directories: &_cmake_cache_directories
  - $MY_CMAKE_DIR

jobs:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - *_cmake_env
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
        - CXX_COMPILER="-DCMAKE_CXX_COMPILER=g++-9"
        - BUILD_CONFIG=
      before_script:
        - *_cmake_build_script
      cache:
        directories:
          - *_cmake_cache_directories

    - os: linux
      arch: arm64
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - *_cmake_env
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
        - CXX_COMPILER="-DCMAKE_CXX_COMPILER=g++-9"
        - BUILD_CONFIG=
      before_script:
        - *_cmake_build_script
      cache:
        directories:
          - *_cmake_cache_directories

    - os: linux
      arch: amd64
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
      env:
        - *_cmake_env
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
        - CXX_COMPILER="-DCMAKE_CXX_COMPILER=clang++-9"
        - BUILD_CONFIG=
      before_script:
        - *_cmake_build_script
      cache:
        directories:
          - *_cmake_cache_directories

    - os: windows
      arch: amd64
      env:
        - *_cmake_env
        - BUILD_TYPE=
        - CXX_COMPILER=
        - BUILD_CONFIG="--config Release"
      before_script:
        - *_cmake_build_script
      cache:
        directories:
          - *_cmake_cache_directories

script:
  - $MY_CMAKE $BUILD_TYPE $CXX_COMPILER -DCMAKE_UNITY_BUILD=ON -S . -B build
  - $MY_CMAKE --build build -j $(nproc) $BUILD_CONFIG
