dist: bionic
jobs:
  include:
    - matrix:
      - language: cpp
        os: linux
        arch:
          - amd64
          - arm64
    - script:
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Release ..
      - cmake --build .
