dist: bionic
language: cpp
os: linux
arch:
  - amd64
  - arm64
compiler:
  - gcc
  - clang
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
jobs:
  include:
    - os: windows
      arch: amd64
      script:
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build . --config Release
