dist: bionic
language: cpp
compiler:
  - clang
  - gcc
arch:
  - amd64
  - arm64
os:
  - linux
  - windows
script:
  - |
    if [ $TRAVIS_OS_NAME == "windows" ]; then
      cmake -S . -B build
      cmake --build build --config Release
    elif [ $TRAVIS_OS_NAME == "linux" ]; then
      cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
      cmake --build build
    else
      echo "Unsupported OS"
      exit 1
    fi