dist: bionic
language: cpp
os:
  - linux
  - windows
arch:
  - amd64
  - arm64
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
jobs:
  include:
    - os: windows
    - script:
      - mkdir build
      - cd build
      - cmake ..
      - cmake --build . --config Release
