language: cpp
dist: bionic
compiler:
  - clang
  - gcc
arch:
  - amd64
  - arm64
os:
  - linux
  - windows
jobs:
  include:
    - stage: "Build"
      if: os = windows
      script:
        - cmake -S . -B build
        - cmake --build build --config Release
    - stage: "Build"
      if: os = linux
      script:
        - cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
        - cmake --build build
