dist: bionic
sudo: false
language: cpp
git:
  depth: 1

jobs:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
        - CXX_COMPILER="-DCMAKE_CXX_COMPILER=g++-9"
        - BUILD_CONFIG=

    - os: windows
      arch: amd64
      env:
        - BUILD_TYPE=
        - CXX_COMPILER=
        - BUILD_CONFIG="--config Release"

script:
  - mkdir build
  - cd build
  - cmake $BUILD_TYPE $CXX_COMPILER ..
  - cmake --build . $BUILD_CONFIG