language: cpp
dist: bionic
compiler:
  - clang
  - gcc
arch:
  - amd64
  - arm64
os:
  - linux
  - windows
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
