dist: bionic
language: cpp
compiler:
  - clang
  - gcc
arch:
  - amd64
  - arm64
os:
  - linux
  - windows
jobs:
  include:
    - if: os = windows
      env: CONFIG="--config Release"
    - if: os = linux
      env: CONFIG=""
script:
  - cmake -S . -B build
  - cmake --build build $CONFIG