dist: bionic
language: cpp
os: linux
arch:
  - amd64
  - arm64
compiler:
  - gcc
  - clang
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
jobs:
  include:
    - os: windows
      arch: amd64
      compiler: msvc
      script:
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build . --config Release
    - os: windows
      arch: amd64
      compiler: gcc
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -G "MSYS Makefiles" ..
        - cmake --build . --config Release
