dist: bionic
language: cpp
branches:
  only:
    - master
git:
  depth: 1

_cmake_build_script: &_cmake_build_script
  - |-
    if [ ! -f $MY_CMAKE ]; then
      cd $HOME
      wget https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2.tar.gz
      tar -xf cmake-3.16.2.tar.gz
      mkdir $MY_CMAKE_DIR
      cmake-3.16.2/bootstrap --prefix=$MY_CMAKE_DIR --parallel=$(nproc)
      make
      make install
      rm -rf cmake-3.16.2.tar.gz cmake-3.16.2/
      cd -
    fi

_cmake_cache_directories: &_cmake_cache_directories
  - $MY_CMAKE_DIR

jobs:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      env:
        - MY_CMAKE_DIR=&HOME/cmake
        - MY_CMAKE=$MY_CMAKE_DIR/bin/cmake
        - BUILD_TYPE="-DCMAKE_BUILD_TYPE=Release"
        - CXX_COMPILER="-DCMAKE_CXX_COMPILER=g++-9"
        - BUILD_CONFIG=
      before_script:
        *_cmake_build_script
      cache:
        directories:
          *_cmake_cache_directories

script:
  - mkdir build
  - cd build
  - $MY_CMAKE $BUILD_TYPE $CXX_COMPILER -DCMAKE_UNITY_BUILD=ON ..
  - $MY_CMAKE --build . $BUILD_CONFIG
