dist: bionic
language: cpp
compiler:
  - clang
  - gcc
arch:
  - amd64
  - arm64
os:
  - linux
  - windows
script:
  - |
    if [ $TRAVIS_OS_NAME == "windows" ]; then
      mkdir build
      cd build
      cmake ..
      cmake --build . --config Release
    elif [ $TRAVIS_OS_NAME == "linux" ]; then
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Release ..
      cmake --build .
    else
      echo "Unsupported OS"
      exit 1
    fi