dist: bionic
language: cpp
os: linux
arch:
  - amd64
  - arm64
jobs:
  include:
    - script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - cmake --build .
