dist: bionic
os:
  - linux
  - windows
jobs:
  include:
    - if: os = windows
      language: cpp
      script:
        - cmake -S . -B build
        - cmake --build build --config Release
    - if: os = linux
      language: cpp
      compiler:
        - clang
        - gcc
      arch:
        - amd64
        - arm64
      script:
        - cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
        - cmake --build build
