language: cpp
dist: bionic
compiler:
  - clang
  - gcc
arch:
  - amd64
  - arm64
os:
  - linux
  - windows
jobs:
  include:
    - stage: build
      if: os = windows
      script: cmake -S . -B build
    - script: cmake --build build --config Release
    - stage: build
      if: os = linux
      script: -DCMAKE_BUILD_TYPE=Release cmake -S . -B build
    - script: cmake --build build
