dist: bionic
sudo: false
language: cpp
git:
  depth: 1

jobs:
  include:
    - os: linux
      arch: amd64
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-9 ..
        - cmake --build .

    - os: windows
      arch: amd64
      script:
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build . --config Release
